// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGPr0Zq1yfmMeJqPblD0goI_jQpuJkbS4',
    appId: '1:7061147228:web:5c5696262347e64bc06099',
    messagingSenderId: '7061147228',
    projectId: 'myapp-fe476',
    authDomain: 'myapp-fe476.firebaseapp.com',
    storageBucket: 'myapp-fe476.firebasestorage.app',
    measurementId: 'G-JCK7K4H4L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5LIazfqRWua9pYoMsAHSpaf52ba1mWPk',
    appId: '1:7061147228:android:1efc91cf5337c8e8c06099',
    messagingSenderId: '7061147228',
    projectId: 'myapp-fe476',
    storageBucket: 'myapp-fe476.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgNPgX3LdazERfoZvOhrnAQZbpY5VsGQQ',
    appId: '1:7061147228:ios:9ca8d2da67ecefb1c06099',
    messagingSenderId: '7061147228',
    projectId: 'myapp-fe476',
    storageBucket: 'myapp-fe476.firebasestorage.app',
    androidClientId: '7061147228-27bo1cb22tqf6o5ciddl7h993q094sa2.apps.googleusercontent.com',
    iosClientId: '7061147228-ljununc2tu28ha5akvt3u2geqj8j7h11.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitchen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgNPgX3LdazERfoZvOhrnAQZbpY5VsGQQ',
    appId: '1:7061147228:ios:9ca8d2da67ecefb1c06099',
    messagingSenderId: '7061147228',
    projectId: 'myapp-fe476',
    storageBucket: 'myapp-fe476.firebasestorage.app',
    androidClientId: '7061147228-27bo1cb22tqf6o5ciddl7h993q094sa2.apps.googleusercontent.com',
    iosClientId: '7061147228-ljununc2tu28ha5akvt3u2geqj8j7h11.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitchen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGPr0Zq1yfmMeJqPblD0goI_jQpuJkbS4',
    appId: '1:7061147228:web:b106054ab62b4ee3c06099',
    messagingSenderId: '7061147228',
    projectId: 'myapp-fe476',
    authDomain: 'myapp-fe476.firebaseapp.com',
    storageBucket: 'myapp-fe476.firebasestorage.app',
    measurementId: 'G-VK71RQD1WH',
  );
}
